Домашнее задание 11 на проверку
PavelRomashin/Playlist pull request #6
Opened 2023-02-28 06:47 UTC by PavelRomashin

Работа на проверку

2023-02-28 08:34 UTC, NoDopezzz requested changes

2023-02-28 08:34 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +    private val notFound = "Ничего не нашлось"
⏫ Стоит всегда помнить о необходимости выносить строки в строковые ресуры - `strings.xml`, как это было в спринте 9

2023-02-28 08:34 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/TrackHolder.kt
> +        trackLength.text = SimpleDateFormat("mm:ss", Locale.getDefault()).format(293000L)
⚠️ Кажется, в метод `format` передается значение из примера. Стоит заменить его на значение из передаваемой модели трека, иначе все треки в плейлисте будут продолжительностью в 04:53))

2023-02-28 08:34 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            if (text == notFound) {
⏫ Чтобы избежать сравнение `String`,  разработчики часто используют следующий подход:
Создают общий класс ошибки, обычно он является `sealed` классом (его еще можно назвать UI State ошибки), в котором указываются способы отображения той или иной ошибки (текст ошибки, изображение ошибки, видна ли кнопка "Обновить" и т.п.).
Затем  создают под каждый вид ошибки отдельный класс или `object`, который наследуется от общего класса. 

Вот пример того, как такой класс может выглядеть.
```

sealed class UIError(
            @StringRes val text: Int,
            @DrawableRes val icon: Int,
            isButtonVisible: Boolean
    ) {
        
        object NotFound : UIError(...)

        ...
    }
```

Метод `showMessage` может лишь принимать объект класса `UIError` и в зависимости от его параметров менять состояния вьюшек

2023-02-28 08:34 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/Track.kt
> +val trackLibrary = ArrayList<Track>()
⏫ В данном случае список треков хранится в глобальной переменной и будет жить всю жизнь приложения. Даже если мы перезайдем на экран "Поиска", мы все равно увидим старый запрос, хотя в поисковой строке пусто.
Советую перенести хранение `trackLibrary` из глобальной переменной в переменную класса `SearchActivity`. 

Но не стоит забывать о необходимости сохранять значение списка при перевороте экрана!

2023-02-28 08:34 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +    private fun showMessage(text: String) {
⏫ После переворота экрана у нас пропадает сообщение об ошибке до тех пор, пока снова не нажмем на кнопку DONE на клавиатуре. Стоит подумать над сохранением состояния экрана при смене конфигурации

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/res/layout-v28/activity_search.xml
> +                    android:fontFamily="@font/ys_display_medium"
⏫ Скорее всего в приложении на разных экранах будут отображаться экраны с ошибками в одном стиле. Чтобы поддержать общую стилистику приложения можем вынести атрибуты оформления в отдельный стиль

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/res/layout-v28/activity_search.xml
> +        android:paddingHorizontal="16dp"
⏫ `layout-v28` используется, если мы хотим поддержать отдельную верстку для устройств с версией SDK-28 и больше. Такое может быть полезно, если например мы используем элементы с атрибутами, которые поддерживаются только начиная с определенной версии SDK, а обратную поддержку не завезли(
Подробнее о папках ресурсов можно почитать в [документации от Google](https://developer.android.com/guide/topics/resources/providing-resources)

В данном случае в нашей верстке ничего специфичного для SDK-28 нет, поэтому мы можем смело уделить всю папку `layout-v28` без последствий и поддерживать только `layout`

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +                updateButton.setOnClickListener { search() }
⏫ Чтобы не выставлять каждый раз при показе ошибки слушателя для кнопки `updateButton`, можно сделать это один раз в методе `onCreate`

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +                updateButton.visibility = View.VISIBLE
⏫ Есть очень хороший котлиновский extension у класса `View` -  `isVisible`. С его помощью можно менять видимость элемента лишь изменением значения `Boolean`
`View.isVisible = true` -> соответствует `View.VISIBLE`
`View.isVisible = false` -> соответствует `View.GONE`

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +                                trackLibrary.addAll(response.body()?.results!!)
⚠️  Если мы получили ошибку на какой-то запрос (или ничего не нашли), и после этого решили изменить запрос или нажать на кнопку "**Обновить**", то после успешного ответа список треков не отобразится на экране, т.к. видимость заглушек не меняется

2023-02-28 08:34 UTC, NoDopezzz commented on app/src/main/res/layout/activity_search.xml
> +                <Button
⚠️ Кнопка "**Обновить**" в темной теме имеет белый текст, который не виден на белом фоне. Советую вынести атрибуты кнопки в стили и добавить стиль для темной темы

<img width="330" alt="image" src="https://user-images.githubusercontent.com/56832972/221797385-11a45edf-8b95-45e6-81a2-4a19f0f8ec12.png">

2023-03-02 09:49 UTC, PavelRomashin commented on app/src/main/res/layout-v28/activity_search.xml
> +        android:paddingHorizontal="16dp"
У меня личный телефон, на котором я тестирую то,что написал, стягивает именно этот лейаут, приходится поэтому дублировать)

2023-03-07 04:31 UTC, merged